apiVersion: v1
kind: ConfigMap
metadata:
  name: holmes-observability-tools
  namespace: holmes-sample
data:
  custom_toolset.yaml: |
    toolsets:
      prometheus/metrics:
        enabled: true
        config:
          prometheus_url: "{{ env.PROMETHEUS_URL }}"
      elasticsearch/data:
        enabled: true
        config:
          api_url: "{{ env.ELASTICSEARCH_URL }}"
          username: "{{ env.ELASTICSEARCH_USERNAME }}"
          password: "{{ env.ELASTICSEARCH_PASSWORD }}"
      elasticsearch/cluster:
        enabled: true
        config:
          api_url: "{{ env.ELASTICSEARCH_URL }}"
          username: "{{ env.ELASTICSEARCH_USERNAME }}"
          password: "{{ env.ELASTICSEARCH_PASSWORD }}"
